name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting the environment up.
      env:
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        ZT_PRIVATE_KEY: ${{ secrets.ZT_PRIVATE_KEY }}
        ZT_NETWORK_ID: ${{ secrets.ZT_NETWORK_ID }}
        NOMACHINE_DMG_URL: ${{ secrets.NOMACHINE_DMG_URL }}
      run: source configure.sh "$USER_PASSWORD" "$VNC_PASSWORD" "$ZT_PRIVATE_KEY" "$ZT_NETWORK_ID" "$NOMACHINE_DMG_URL"
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
    - name: Sleeping...
      run: sleep 21000
